### ISSUE TITLE
[BUG] Property 'getTokenBalance' does not exist on type 'PrimeSdk'.ts(2339)

### ISSUE THREAD

**Issue by francelwebdev** [etherspot/etherspot-prime-sdk#80]
### Describe the bug

I want to get the balance of an token of a SCW address. When i call the function getTokenBalance on the instance of PrimeSdk i get :Property 'getTokenBalance' does not exist on type 'PrimeSdk'.ts(2339)

### Expected behavior

I found the function getTokenBalance(tokenAddress: string) in the documentation and I expected the function to exist and return the balance

### Operating system

Linux

### Prime SDK version or commit hash

latest

**Comment by vignesha22** [comment]
yes since we don't have a function called as getTokenBalance, we have only getNativeBalance function which returns your native balance on the sw. For fetching token balances, please refer the example 05-get-account-balances.ts which has an optional parameter called as `tokens` while calling the function primeSdk.getAccountBalance
